Repository cloudforet-io/identity, pull requests merged in 2024-03, with the labels that each got.

#200 Add plugin interface and skeleton code
  src/spaceone/identity/managed_resource/provider/azure.yaml
  src/spaceone/identity/plugin/__init__.py
  src/spaceone/identity/plugin/account_collector/__init__.py
  src/spaceone/identity/plugin/account_collector/conf/__init__.py
  src/spaceone/identity/plugin/account_collector/conf/global_conf.py
  src/spaceone/identity/plugin/account_collector/interface/__init__.py
  src/spaceone/identity/plugin/account_collector/interface/grpc/__init__.py
  src/spaceone/identity/plugin/account_collector/interface/grpc/account_collector.py
  src/spaceone/identity/plugin/account_collector/lib/__init__.py
  src/spaceone/identity/plugin/account_collector/lib/server.py
  src/spaceone/identity/plugin/account_collector/model/__init__.py
  src/spaceone/identity/plugin/account_collector/model/account_collect_request.py
  src/spaceone/identity/plugin/account_collector/model/account_collect_response.py
  src/spaceone/identity/plugin/account_collector/service/__init__.py
  src/spaceone/identity/plugin/account_collector/service/account_collector_service.py
  src/spaceone/identity/plugin/account_collector/skeleton/__init__.py
  src/spaceone/identity/plugin/account_collector/skeleton/main.py
Labels: enhancement

#201 Fix typo at trusted account response
  src/spaceone/identity/model/trusted_account/response.py
Labels: bug

#204 Udate global config for QUEUES settings
  src/spaceone/identity/conf/global_conf.py
Labels: enhancement

#205 Fix BaseDict' object has no attribute 'to_dict' error when sync
  src/spaceone/identity/manager/__init__.py
  src/spaceone/identity/manager/account_collector_plugin_manager.py
  src/spaceone/identity/service/trusted_account_service.py
Labels: bug

#206 Fix job_id prefix 'pg' to 'job'
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/model/job/database.py
  src/spaceone/identity/model/job/response.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/trusted_account_service.py
Labels: bug

#207 Modify scheduler sync parameter
  src/spaceone/identity/interface/task/v1/trusted_account_sync_scheduler.py
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/model/job/database.py
  src/spaceone/identity/model/job/response.py
  src/spaceone/identity/service/job_service.py
Labels: bug

#208 Add trusted account sync api
  src/spaceone/identity/manager/__init__.py
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#209 Add trusted secret get data at secret manager
  src/spaceone/identity/interface/task/v1/trusted_account_sync_scheduler.py
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/__init__.py
  src/spaceone/identity/service/job_service.py
Labels: bug, enhancement

#211 Add api for user add and remove at ProjectGroup
  src/spaceone/identity/interface/grpc/project_group.py
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/model/project_group/database.py
  src/spaceone/identity/model/project_group/request.py
  src/spaceone/identity/model/project_group/response.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/project_group_service.py
Labels: enhancement

#212 Add 'state' field for Role and apis 'enable', 'disable'
  src/spaceone/identity/interface/grpc/role.py
  src/spaceone/identity/manager/role_manager.py
  src/spaceone/identity/model/role/database.py
  src/spaceone/identity/model/role/request.py
  src/spaceone/identity/model/role/response.py
  src/spaceone/identity/service/role_service.py
Labels: enhancement

#213 Add users projects in project group when grant token
  src/spaceone/identity/manager/project_group_manager.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement, pass/signedoff

#214 Add create project_group and workspace when sync trusted account
  src/spaceone/identity/connector/account_collector_plugin_connector.py
  src/spaceone/identity/manager/account_collector_plugin_manager.py
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/provider_service.py
Labels: enhancement

#215 Add permission for workspace_member for user add and remove
  src/spaceone/identity/error/error_project_group.py
  src/spaceone/identity/manager/project_group_manager.py
  src/spaceone/identity/service/project_group_service.py
Labels: enhancement

#217 fix response message at ta sync api
  src/spaceone/identity/interface/grpc/trusted_account.py
  src/spaceone/identity/model/job/database.py
  src/spaceone/identity/model/job/response.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#218 feat: remove permission at add, remove users at ProjectGroupMember (#…
  src/spaceone/identity/service/project_group_service.py
Labels: pass/signedoff

#219 Add service account agent mode
  pkg/pip_requirements.txt
  src/spaceone/identity/interface/grpc/service_account.py
  src/spaceone/identity/lib/key_generator.py
  src/spaceone/identity/manager/app_manager.py
  src/spaceone/identity/manager/client_secret_manager.py
  src/spaceone/identity/model/app/database.py
  src/spaceone/identity/model/app/response.py
  src/spaceone/identity/model/service_account/database.py
  src/spaceone/identity/model/service_account/request.py
  src/spaceone/identity/model/service_account/response.py
  src/spaceone/identity/service/app_service.py
  src/spaceone/identity/service/service_account_service.py
Labels: pass/signedoff

#220 Modify sa, project, project_group, workspace response model
  src/spaceone/identity/model/project/database.py
  src/spaceone/identity/model/project/response.py
  src/spaceone/identity/model/project_group/database.py
  src/spaceone/identity/model/project_group/response.py
  src/spaceone/identity/model/service_account/database.py
  src/spaceone/identity/model/service_account/response.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#221 Add job error message
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#222 Fix to_dict error when account sync (#199)
  src/spaceone/identity/service/job_service.py
Labels: bug

#223 Fix get secret_data method
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/job_service.py
Labels: bug

#224 Modify identity plugin skeleton code
  src/spaceone/identity/plugin/account_collector/model/account_collect_response.py
  src/spaceone/identity/plugin/account_collector/skeleton/main.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#225 Fix parameter field when create project
  src/spaceone/identity/service/job_service.py
Labels: enhancement
