Repository cloudforet-io/identity, pull requests merged in 2024-10, with the labels that each got.

#384 Modify code such that delete role binding when delete workspace
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, fail/signedoff

#385 Modify code such that there are no users when creating a workspace group
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#386 Refactor all of the codes for maintenance
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, fail/signedoff

#387 Add return value
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, pass/signedoff

#388 Refactor code for maintenance
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#389 Extend old_user_ids and new_user_ids, not intialization
  src/spaceone/identity/manager/workspace_group_manager.py
Labels: bug, enhancement, pass/signedoff

#390 Update method for getting unique user_ids
  src/spaceone/identity/manager/workspace_group_manager.py
Labels: enhancement, pass/signedoff

#391 Refactor get_workspace_groups method
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, fail/signedoff

#392 Fix add users when there is more than 1 workspace
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, pass/signedoff

#394 fix error when creating secret_id is None during auto sync
  src/spaceone/identity/service/job_service.py
Labels: bug

#395 Implement OTP for multi-factor authentication (MFA)
  pkg/pip_requirements.txt
  src/setup.py
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/manager/mfa_manager/__init__.py
  src/spaceone/identity/manager/mfa_manager/base.py
  src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
  src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/manager/token_manager/mfa_token_manager.py
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement, fail/signedoff

#396 Fix error in OTP confirm when createing user_ secret_id
  src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py
Labels: enhancement, fail/signedoff

#398 Add logic to delete user_secret when disabling MFA if mfa_type is OTP
  src/spaceone/identity/service/user_service.py
Labels: enhancement, fail/signedoff

#400 Fix typo in Token issue error message when MFA required
  src/spaceone/identity/error/error_mfa.py
Labels: fail/signedoff

#401 Fix permission error when deleting user_secret in user_service disable_mfa method
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/user_service.py
Labels: enhancement, fail/signedoff

#402 Add new feature for setting refresh timeout for domain admin user
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/interface/grpc/user_profile.py
  src/spaceone/identity/manager/token_manager/base.py
  src/spaceone/identity/model/user/database.py
  src/spaceone/identity/model/user/response.py
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: enhancement

#403 Modify feature for setting refresh 'UserProfile' -> 'User'
  src/spaceone/identity/interface/grpc/user.py
  src/spaceone/identity/interface/grpc/user_profile.py
  src/spaceone/identity/manager/token_manager/base.py
  src/spaceone/identity/model/user/request.py
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: enhancement
