Repository cloudforet-io/identity, pull requests merged in 2024-11, with the labels that each got.

#404 Update MFA requirement to apply only for LOCAL auth_type
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement, fail/signedoff

#405 Fix update service account with secret
  src/spaceone/identity/service/service_account_service.py
  src/spaceone/identity/service/token_service.py
Labels: bug

#406 Update MFA requirement to prevent enforcement for EXTERNAL auth_type with SAML protocol
  src/spaceone/identity/service/token_service.py
Labels: enhancement, fail/signedoff

#407 Add endpoints values at token payload
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/lib/key_generator.py
  src/spaceone/identity/manager/token_manager/base.py
  src/spaceone/identity/service/user_service.py
Labels: enhancement, pass/signedoff

#410 Remove endpoints at token payload
  src/spaceone/identity/lib/key_generator.py
  src/spaceone/identity/model/user_profile/response.py
  src/spaceone/identity/service/user_profile_service.py
Labels: documentation

#411 Remove unused parameter when generate token
  src/spaceone/identity/manager/token_manager/base.py
Labels: bug
