Repository cloudforet-io/identity, pull requests merged in 2024-12, with the labels that each got.

#412 Create service account analyze function for metric data.
  src/spaceone/identity/interface/grpc/service_account.py
  src/spaceone/identity/manager/service_account_manager.py
  src/spaceone/identity/model/service_account/request.py
  src/spaceone/identity/service/service_account_service.py
Labels: pass/signedoff

#413 fix: add validation to package.delete
  src/spaceone/identity/manager/opsflow_manager.py
  src/spaceone/identity/service/package_service.py
Labels: pass/signedoff

#414 fix: add validation to package.delete
  src/spaceone/identity/manager/opsflow_manager.py
  src/spaceone/identity/service/package_service.py
Labels: pass/signedoff

#415 Improve email verification code generation with python secrets
  src/spaceone/identity/manager/mfa_manager/base.py
  src/spaceone/identity/manager/mfa_manager/otp_mfa_manager.py
  src/spaceone/identity/manager/token_manager/base.py
Labels: enhancement, pass/signedoff, fail/signedoff

#416 Add domain_display_name to reset password email for user added
  src/spaceone/identity/manager/email_manager.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
  src/spaceone/identity/template/reset_pwd_link_when_user_added_en.html
  src/spaceone/identity/template/reset_pwd_link_when_user_added_ja.html
  src/spaceone/identity/template/reset_pwd_link_when_user_added_ko.html
  src/spaceone/identity/template/sso_invite_user_link_en.html
  src/spaceone/identity/template/sso_invite_user_link_ja.html
  src/spaceone/identity/template/sso_invite_user_link_ko.html
  src/spaceone/identity/template/temp_pwd_when_user_added_en.html
  src/spaceone/identity/template/temp_pwd_when_user_added_ja.html
  src/spaceone/identity/template/temp_pwd_when_user_added_ko.html
Labels: enhancement, pass/signedoff, fail/signedoff

#417 Add logic to block token issue after repeated attempts
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/error/error_authentication.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement

#418 Modify logic to block token issue after repeated attempts
  src/spaceone/identity/service/token_service.py
Labels: enhancement

#419 Add update_password api at UserProfile
  src/spaceone/identity/error/error_user.py
  src/spaceone/identity/interface/grpc/user_profile.py
  src/spaceone/identity/manager/user_manager.py
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement

#420 Modify global_conf.py
  src/spaceone/identity/conf/global_conf.py
Labels: enhancement, pass/signedoff
