Repository cloudforet-io/identity, pull requests merged in 2024-04, with the labels that each got.

#226 Add managed resource modify rule
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/manager/resource_manager.py
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/manager/service_account_manager.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/project_group_service.py
  src/spaceone/identity/service/project_service.py
  src/spaceone/identity/service/service_account_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement

#227 Modify get-workspace api response
  src/spaceone/identity/interface/grpc/user_profile.py
  src/spaceone/identity/model/user_profile/response.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement

#228 Add plugin_options for trusted_account
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/model/job/database.py
  src/spaceone/identity/model/job/response.py
  src/spaceone/identity/model/trusted_account/database.py
  src/spaceone/identity/model/trusted_account/request.py
  src/spaceone/identity/model/trusted_account/response.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/trusted_account_service.py
Labels: enhancement

#229 Fix provider plugin update api
  src/spaceone/identity/service/provider_service.py
  src/spaceone/identity/service/service_account_service.py
Labels: bug

#230 Add metadata field at provider plugin_info
  src/spaceone/identity/model/provider/response.py
Labels: enhancement

#231 Add is_managed field at Workspace model
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/service/job_service.py
Labels: bug

#232 Add role_name at MyWorkspaceInfo
  src/spaceone/identity/model/user_profile/response.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement

#233 Modify delete_secrete at secret manager
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#234 Add skip condition when try to save duplicated resource
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement

#235 Modify updatable_fields at Job model
  src/spaceone/identity/model/job/database.py
Labels: enhancement

#236 Modify unique rule for service account name
  src/spaceone/identity/model/service_account/database.py
Labels: enhancement

#238 Add insert trusted account id logic at auto synced resource
  src/spaceone/identity/manager/job_manager.py
  src/spaceone/identity/manager/resource_manager.py
  src/spaceone/identity/model/project/database.py
  src/spaceone/identity/model/project/response.py
  src/spaceone/identity/model/project_group/database.py
  src/spaceone/identity/model/project_group/response.py
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#239 Update google cloud provider at managed_resource
  src/spaceone/identity/managed_resource/provider/google_cloud.yaml
Labels: enhancement

#240 Modify unique rule for service account name
  src/spaceone/identity/manager/resource_manager.py
  src/spaceone/identity/model/service_account/database.py
Labels: bug, enhancement, pass/signedoff

#241 fix managed resource by auto sync delete condition
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/manager/resource_manager.py
  src/spaceone/identity/model/service_account/database.py
Labels: bug

#242 Modify error message from custom error
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/error/custom.py
Labels: enhancement

#243 Update managed provider version (aws)
  src/spaceone/identity/managed_resource/provider/aws.yaml
  src/spaceone/identity/managed_resource/schema/azure_secret_multi_tenant.yaml
  src/spaceone/identity/managed_resource/schema/azure_service_account.yaml
  src/spaceone/identity/manager/schema_manager.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#244 Update helm chart version 1.3.14
  deploy/helm/Chart.yaml
  deploy/helm/config/config.yaml
Labels: enhancement

#246 Fix get workspace parameter order error
  src/spaceone/identity/service/job_service.py
Labels: bug

#247 Added 2 new schemas needed for aws account sync function
  src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml
  src/spaceone/identity/managed_resource/schema/aws_security_ou_schema.yaml
  src/spaceone/identity/managed_resource/schema/aws_trusted_account.yaml
Labels: fail/signedoff

#248 Added version to each new schema
  src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml
  src/spaceone/identity/managed_resource/schema/aws_security_ou_schema.yaml
Labels: fail/signedoff

#250 Add permission for WORKSPACE MEMBER when job read
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/model/job/request.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement, pass/signedoff

#251 Add trusted_account_id at managed workspace
  src/spaceone/identity/service/job_service.py
Labels: bug

#253 Fix job status typo error
  src/spaceone/identity/model/job/response.py
  src/spaceone/identity/model/project_group/database.py
Labels: bug

#254 Add debug code
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#255 Add duplicated workspace create logic
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#256 Merge agent_info with app_info
  src/spaceone/identity/model/agent/response.py
  src/spaceone/identity/service/agent_service.py
Labels: enhancement, pass/signedoff

#258 Modify yaml file of google cloud settings
  src/spaceone/identity/managed_resource/provider/google_cloud.yaml
Labels: fail/signedoff

#259 Modify debug code
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#260 Add Agent list query
  src/spaceone/identity/service/agent_service.py
Labels: enhancement, fail/signedoff

#262 Modify error msg
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement

#263 Modify error code
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/manager/resource_manager.py
  src/spaceone/identity/service/project_group_service.py
  src/spaceone/identity/service/project_service.py
  src/spaceone/identity/service/service_account_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement

#264 fix typo
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/service/workspace_service.py
Labels: bug

#265 Fix create workspace error when skip project group
  src/spaceone/identity/service/job_service.py
Labels: bug, pass/signedoff

#266 Fix update project and project group logic
  src/spaceone/identity/service/job_service.py
Labels: bug, pass/signedoff

#268 Modify max length of project and project group name
  src/spaceone/identity/model/project/database.py
  src/spaceone/identity/model/project_group/database.py
Labels: enhancement

#269 Add managed resource and schema of k8s
  src/spaceone/identity/managed_resource/provider/kubernetes.yaml
  src/spaceone/identity/managed_resource/schema/kubernetes_service_account.yaml
Labels: enhancement, pass/signedoff

#270 Fix max length of project name
  src/spaceone/identity/model/project/database.py
Labels: bug

#271 Modify field 'reference_id' -> 'references' at WorkspaceInfo
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#272 None type error when check workspace references value
  src/spaceone/identity/service/job_service.py
Labels: bug

#273 Updated schemas related to control tower
  src/spaceone/identity/managed_resource/provider/aws.yaml
  src/spaceone/identity/managed_resource/schema/aws_control_tower_schema.yaml
Labels: pass/signedoff

#275 Fix the error of not saving references
  src/spaceone/identity/service/job_service.py
Labels: bug

#277 Modify external auth content to identity provider
  src/spaceone/identity/manager/email_manager.py
  src/spaceone/identity/service/job_service.py
  src/spaceone/identity/service/user_service.py
  src/spaceone/identity/template/authentication_code_ja.html
  src/spaceone/identity/template/sso_invite_user_link_ja.html
  src/spaceone/identity/template/sso_invite_user_link_ko.html
  src/spaceone/identity/template/verification_MFA_code_ja.html
Labels: enhancement
