Repository cloudforet-io/identity, pull requests merged in 2024-08, with the labels that each got.

#298 Apply black code formatter
  src/spaceone/identity/connector/account_collector_plugin_connector.py
  src/spaceone/identity/error/error_project.py
  src/spaceone/identity/manager/account_collector_plugin_manager.py
  src/spaceone/identity/manager/endpoint_manager.py
  src/spaceone/identity/manager/managed_resource_manager.py
  src/spaceone/identity/manager/mfa_manager/base.py
  src/spaceone/identity/manager/mfa_manager/email_mfa_manger.py
  src/spaceone/identity/manager/project_group_manager.py
  src/spaceone/identity/manager/provider_manager.py
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/manager/token_manager/external_token_manager.py
  src/spaceone/identity/model/domain/database.py
  src/spaceone/identity/model/external_auth/database.py
  src/spaceone/identity/model/schema/database.py
  src/spaceone/identity/model/schema/request.py
  src/spaceone/identity/model/schema/response.py
  src/spaceone/identity/service/app_service.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/service_account_service.py
  src/spaceone/identity/service/workspace_user_service.py
Labels: enhancement, pass/signedoff

#299 Modify update secret logic when service account auto sync
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/job_service.py
Labels: enhancement

#300 Fix list secrets method at secret manager
  src/spaceone/identity/manager/secret_manager.py
  src/spaceone/identity/service/job_service.py
Labels: bug, pass/signedoff

#301 Remove domain_id parameter when request to secret service
  src/spaceone/identity/service/job_service.py
Labels: bug

#302 Add new feature for App Service with 'Workspace Member' role
  src/spaceone/identity/model/app/database.py
  src/spaceone/identity/model/app/request.py
  src/spaceone/identity/model/app/response.py
  src/spaceone/identity/service/app_service.py
  src/spaceone/identity/service/user_service.py
Labels: bug, enhancement, pass/signedoff

#303 Add workspace group feature
  .gitignore
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/interface/grpc/__init__.py
  src/spaceone/identity/interface/grpc/workspace_group.py
  src/spaceone/identity/manager/user_manager.py
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/model/role_binding/database.py
  src/spaceone/identity/model/role_binding/response.py
  src/spaceone/identity/model/workspace_group/__init__.py
  src/spaceone/identity/model/workspace_group/database.py
  src/spaceone/identity/model/workspace_group/request.py
  src/spaceone/identity/model/workspace_group/response.py
  src/spaceone/identity/model/workspace_user/response.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#304 Add docstring
  src/spaceone/identity/model/workspace_group/request.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#305 Add workspace group details prototype
  src/spaceone/identity/interface/grpc/__init__.py
  src/spaceone/identity/interface/grpc/workspace_group_details.py
  src/spaceone/identity/model/workspace_group_details/__init__.py
  src/spaceone/identity/model/workspace_group_details/database.py
  src/spaceone/identity/model/workspace_group_details/request.py
  src/spaceone/identity/model/workspace_group_details/response.py
  src/spaceone/identity/service/workspace_group_details_service.py
Labels: enhancement, pass/signedoff

#306 Modify python-core version because of protobuf issue
  Dockerfile
Labels: bug, pass/signedoff

#307 Modify python-core version because of protobuf issue
  Dockerfile
Labels: bug, pass/signedoff

#308 Modify python-core version because of protobuf issue
  Dockerfile
Labels: bug, pass/signedoff

#309 Modify python-core version because of protobuf issue
  Dockerfile
Labels: bug, pass/signedoff

#310 Modify python-core version because of protobuf issue
  Dockerfile
  pkg/pip_requirements.txt
Labels: bug, pass/signedoff

#311 Modify pip_requirements because of protobuf issue
  pkg/pip_requirements.txt
Labels: bug, pass/signedoff

#312 Modify protobuf version because of protobuf issue
  pkg/pip_requirements.txt
Labels: bug, pass/signedoff

#315 Modify protobuf version because of protobuf issue
  pkg/pip_requirements.txt
Labels: bug, pass/signedoff

#316 Upgrade protobuf version because of protobuf issue
  Dockerfile
  pkg/pip_requirements.txt
Labels: bug, pass/signedoff

#318 Add user_id which is injected from auth
  Dockerfile
  src/spaceone/identity/model/workspace_group_details/request.py
  src/spaceone/identity/service/workspace_group_details_service.py
Labels: enhancement, pass/signedoff

#319 Modify user type to list of dictionary
  src/spaceone/identity/model/workspace_group/database.py
  src/spaceone/identity/model/workspace_group/request.py
  src/spaceone/identity/model/workspace_group/response.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#320 Add WorkspaceGroupUser skeleton code
  src/spaceone/identity/interface/grpc/__init__.py
  src/spaceone/identity/interface/grpc/workspace_group_details.py
  src/spaceone/identity/interface/grpc/workspace_group_user.py
  src/spaceone/identity/manager/workspace_user_manager.py
  src/spaceone/identity/model/workspace_group_details/database.py
  src/spaceone/identity/model/workspace_group_details/request.py
  src/spaceone/identity/model/workspace_group_user/__init__.py
  src/spaceone/identity/model/workspace_group_user/request.py
  src/spaceone/identity/model/workspace_group_user/response.py
  src/spaceone/identity/service/workspace_group_details_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
  src/spaceone/identity/service/workspace_user_service.py
Labels: enhancement, pass/signedoff

#321 Add update_role method and delete role_binding when remove workspaces&users
  src/spaceone/identity/error/error_role.py
  src/spaceone/identity/interface/grpc/workspace_group.py
  src/spaceone/identity/model/workspace_group/request.py
  src/spaceone/identity/model/workspace_group/response.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#323 Fix the bug and add find, get, list, and stat methods in WorkspaceGroupUser
  .gitignore
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/model/workspace_group_user/request.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement, pass/signedoff

#324 Modify code when there are no workspace users
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, enhancement

#326 Add add, remove, update_role methods
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/model/workspace_group_user/request.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#327 Change variable name
  src/spaceone/identity/model/workspace_group_user/request.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#328 Delete role bindings when the workspace group is deleted
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#329 Remove role_id when update the role
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#330 Add list_basic_role method
  src/spaceone/identity/interface/grpc/role.py
  src/spaceone/identity/manager/role_manager.py
  src/spaceone/identity/model/__init__.py
  src/spaceone/identity/model/role/request.py
  src/spaceone/identity/model/role/response.py
  src/spaceone/identity/service/role_service.py
Labels: enhancement, pass/signedoff

#332 Add user_count to workspace
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/model/role_binding/database.py
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/role_binding_service.py
Labels: enhancement, pass/signedoff

#333 Modify workspace member access to get_workspace_groups api
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff
