Repository cloudforet-io/identity, pull requests merged in 2024-06, with the labels that each got.

#285 Modify service account limit '1000' -> '2000'
  src/spaceone/identity/service/service_account_service.py
Labels: enhancement

#286 Modify 'user_id' max length 40->60
  src/spaceone/identity/model/user/database.py
Labels: enhancement, pass/signedoff

#288 Add edge case for required fields
  src/spaceone/identity/error/error_external_auth.py
  src/spaceone/identity/service/external_auth_service.py
Labels: enhancement

#289 Fix default role type when grant token
  src/spaceone/identity/service/token_service.py
Labels: bug

#291 Add default timezone when create user
  src/spaceone/identity/service/user_service.py
  src/spaceone/identity/template/reset_pwd_link_when_pw_forgotten_en.html
  src/spaceone/identity/template/reset_pwd_link_when_user_added_en.html
Labels: bug, enhancement
