Repository cloudforet-io/identity, pull requests merged in 2024-05, with the labels that each got.

#278 Modify role types to Agent get, list
  src/spaceone/identity/service/agent_service.py
Labels: bug, pass/signedoff

#279 Add check required actions when grant token
  src/spaceone/identity/error/error_authentication.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement

#280 Add DOMAIN_ADMIN role type to Agent get, list
  src/spaceone/identity/service/agent_service.py
Labels: bug, pass/signedoff

#281 Add external_auth skeleton code
  src/spaceone/identity/plugin/external_auth/__init__.py
  src/spaceone/identity/plugin/external_auth/conf/__init__.py
  src/spaceone/identity/plugin/external_auth/conf/global_conf.py
  src/spaceone/identity/plugin/external_auth/interface/__init__.py
  src/spaceone/identity/plugin/external_auth/interface/grpc/__init__.py
  src/spaceone/identity/plugin/external_auth/interface/grpc/external_auth.py
  src/spaceone/identity/plugin/external_auth/lib/__init__.py
  src/spaceone/identity/plugin/external_auth/lib/server.py
  src/spaceone/identity/plugin/external_auth/model/__init__.py
  src/spaceone/identity/plugin/external_auth/model/external_auth_request.py
  src/spaceone/identity/plugin/external_auth/model/external_auth_response.py
  src/spaceone/identity/plugin/external_auth/service/__init__.py
  src/spaceone/identity/plugin/external_auth/service/external_auth_service.py
  src/spaceone/identity/plugin/external_auth/skeleton/__init__.py
  src/spaceone/identity/plugin/external_auth/skeleton/main.py
Labels: enhancement, pass/signedoff

#282 Modify user_id uses after user create
  src/spaceone/identity/service/user_service.py
Labels: enhancement

#283 Fix wrong import of UserResponse
  src/spaceone/identity/plugin/external_auth/service/external_auth_service.py
Labels: bug, pass/signedoff

#284 Change variable group_id to group of UserResponse
  src/spaceone/identity/plugin/external_auth/model/external_auth_response.py
Labels: bug, pass/signedoff
