Repository cloudforet-io/identity, pull requests merged in 2024-09, with the labels that each got.

#334 Modify role binding code when workspace_vo exist
  src/spaceone/identity/service/role_binding_service.py
Labels: bug, pass/signedoff

#335 Add custom errors
  src/spaceone/identity/error/custom.py
Labels: bug, pass/signedoff

#336 Add worksapce_group_id to the workspace database
  src/spaceone/identity/model/workspace/database.py
Labels: enhancement, pass/signedoff

#337 Add delete rolebinding debug code
  src/spaceone/identity/manager/role_binding_manager.py
Labels: enhancement

#338 Add safe delete role logic
  src/spaceone/identity/error/custom.py
  src/spaceone/identity/service/role_service.py
Labels: enhancement

#339 Rollback role_binding_info to the dictionary in the workspace user
  src/spaceone/identity/manager/workspace_user_manager.py
  src/spaceone/identity/model/workspace_user/response.py
Labels: enhancement, pass/signedoff

#340 Update workspace group
  src/spaceone/identity/interface/grpc/workspace_group.py
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/model/workspace_group/database.py
  src/spaceone/identity/model/workspace_group/request.py
  src/spaceone/identity/model/workspace_group/response.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#341 Modify workspace group manager
  src/spaceone/identity/manager/workspace_group_manager.py
Labels: enhancement, fail/signedoff

#342 Add change_workspace_group api
  src/spaceone/identity/interface/grpc/workspace.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/model/workspace/request.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#343 Modify parameter
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#344 Modify WorkspaceGroupUser APIs
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/model/workspace_group_user/response.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, fail/signedoff

#346 Update get_workspace_groups API of UserProfile
  src/spaceone/identity/model/user_profile/response.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#347 Add user_name and state when get the WorkspaceGroup
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#348 Add user_name and state when listing the WorkspaceGroup
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#349 Refactor the code and update workspace group user
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/model/workspace_group_user/response.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#350 Modify code when there are no users in the WorkspaceGroup
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#351 Modify code to get audience, not user_id
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#352 Refactor code such that unify workspace group user response
  src/spaceone/identity/model/workspace_group_user/response.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#353 Update to ParseDict from dict_to_message
  src/spaceone/identity/interface/grpc/workspace_group_user.py
Labels: enhancement, pass/signedoff

#354 Refactor code and modify get_workspace_groups
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: enhancement, pass/signedoff

#355 Refactor code such that unify debug code
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#356 Modify code such that when deleting the user and adding the `workspace_group_id` filter
  src/spaceone/identity/manager/user_manager.py
  src/spaceone/identity/service/user_profile_service.py
Labels: enhancement, pass/signedoff

#357 Add the workspace_count field to workspace_group and refactor the code
  src/spaceone/identity/manager/workspace_group_manager.py
  src/spaceone/identity/model/workspace_group/database.py
  src/spaceone/identity/model/workspace_group/response.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#358 Add unique user_id to workspace group although the user has workspaces
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#359 Add changed_at to Workspace and modify the list of Workspace
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/model/workspace/response.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#360 Remove workspaces field of workspace_group_info
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#361 Remove logic for creating combined-role
  src/spaceone/identity/model/token/response.py
  src/spaceone/identity/model/workspace/database.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement

#362 Modify code when changing workspace's workspace group
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#363 Modify code when adding users to the workspace group
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement, pass/signedoff

#365 Update workspace user_count when remove a user from a workspac_group
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, enhancement, pass/signedoff

#366 Modify params code when workspace_id is None
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#367 Modify exclude_unset option and database index
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/model/workspace_group/database.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: enhancement, pass/signedoff

#369 When adding a workspace from A to B, update the user_count of workspaces
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/model/user_profile/response.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#370 Modify when deleting workspace A from Workspace GroupA, all role bindings are deleted to related to Workspace GroupA
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#371 Remove code such that find Mongodb nested document
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: enhancement, pass/signedoff

#372 Convert type when calling the add_user_name_and_state_to_users method
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, pass/signedoff

#373 Change from dict type to object type
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement, pass/signedoff

#374 Add WorkspaceGroup object type
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, enhancement, pass/signedoff

#375 Modify get_workspace_groups
  src/spaceone/identity/service/user_profile_service.py
Labels: bug, pass/signedoff

#376 Modify workspace_group_info type
  src/spaceone/identity/service/user_profile_service.py
Labels: bug, pass/signedoff

#377 Modify code when workspace group users is None
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, pass/signedoff

#378 Modify code when a user is not a dict type
  src/spaceone/identity/service/workspace_group_service.py
Labels: bug, enhancement, pass/signedoff

#379 Modify code when updating role type of USER
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement

#380 Delete workspace role binding when workspace group is added
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#381 Modify code such that deleted original users when adding workspace to workspace group
  src/spaceone/identity/service/workspace_service.py
Labels: bug, enhancement, pass/signedoff

#382 Modify code such that a user has an admin role type in case
  .gitignore
  src/spaceone/identity/manager/workspace_group_user_manager.py
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement, pass/signedoff

#383 Can remove any user when user is a domain
  src/spaceone/identity/service/workspace_group_user_service.py
Labels: bug, enhancement, pass/signedoff
