Repository cloudforet-io/identity, pull requests merged in 2025-01, with the labels that each got.

#423 Add internal_endpoint to endpoint list
  src/spaceone/identity/manager/endpoint_manager.py
  src/spaceone/identity/model/endpoint/request.py
  src/spaceone/identity/model/endpoint/response.py
  src/spaceone/identity/service/endpoint_service.py
Labels: enhancement, pass/signedoff

#424 Add user_groups info at token payload
  src/spaceone/identity/lib/key_generator.py
  src/spaceone/identity/manager/token_manager/base.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement

#425 fix update expired_at on token regeneration
  src/spaceone/identity/service/app_service.py
Labels: bug

#426 Fix deletion issue for role_binding with DOMAIN_ADMIN role_type
  src/spaceone/identity/service/role_binding_service.py
Labels: enhancement, pass/signedoff

#427 Remove password field from UserProfile Update
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/service/user_profile_service.py
Labels: pass/signedoff

#428 Add injected params at token when user use reset_password
  src/spaceone/identity/manager/token_manager/base.py
  src/spaceone/identity/model/user_profile/request.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: enhancement

#429 Grant token error when get user groups with none type error
  src/spaceone/identity/service/token_service.py
Labels: bug
