Repository cloudforet-io/identity, pull requests merged in 2025-08, with the labels that each got.

#467 feat: add token grant type restriction logic in TokenService
  Dockerfile
  src/spaceone/identity/model/user/request.py
  src/spaceone/identity/service/token_service.py
Labels: pass/signedoff

#468 fix: prevent refresh token issuance when MFA enforcement is active
  src/spaceone/identity/error/error_mfa.py
  src/spaceone/identity/service/token_service.py
Labels: pass/signedoff

#471 fix: remove unnecessary logging in TokenService
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#473 feat: Enhances role binding deletion checks
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#474 chore: Imports SecretManager for OTP checks
  src/spaceone/identity/error/error_mfa.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#475 feat: Updates user state after MFA verification
  src/spaceone/identity/manager/token_manager/mfa_token_manager.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#476 refactor: Change MFA activation conditions
  src/spaceone/identity/service/token_service.py
Labels: pass/signedoff

#472 feat: update MFA token issuance logic
  src/spaceone/identity/error/error_mfa.py
  src/spaceone/identity/manager/token_manager/mfa_token_manager.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#479 feat: resolve circular dependency and improve workspace user count synchronization
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: pass/signedoff

#481 refactor: move workspace delete business logic from manager to service
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: pass/signedoff

#482 Add error handling for role updates assigned by workspace groups
  src/spaceone/identity/error/error_role.py
  src/spaceone/identity/model/user/request.py
  src/spaceone/identity/service/role_binding_service.py
Labels: enhancement, pass/signedoff

#484 refactor: Refactors UserProfile MFA state handling
  src/spaceone/identity/service/user_profile_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#485 reafactor: Remove the rule that a workspace must always have one owner
  src/spaceone/identity/manager/role_binding_manager.py
  src/spaceone/identity/manager/user_manager.py
  src/spaceone/identity/service/domain_service.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/role_service.py
  src/spaceone/identity/service/system_service.py
  src/spaceone/identity/service/user_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: pass/signedoff

#486 Improve logging for authentication and token issue
  src/spaceone/identity/manager/token_manager/local_token_manager.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement, pass/signedoff

#487 fix: Avoids unnecessary workspace retrieval
  src/spaceone/identity/service/domain_service.py
  src/spaceone/identity/service/role_binding_service.py
  src/spaceone/identity/service/system_service.py
  src/spaceone/identity/service/user_service.py
  src/spaceone/identity/service/workspace_group_service.py
  src/spaceone/identity/service/workspace_service.py
Labels: pass/signedoff

#492 Fix typo
  src/spaceone/identity/manager/token_manager/local_token_manager.py
  src/spaceone/identity/service/token_service.py
Labels: enhancement, pass/signedoff, fail/signedoff
