Repository cloudforet-io/identity, pull requests merged in 2025-07, with the labels that each got.

#445 fix: update role types for project and service account creation
  src/spaceone/identity/service/project_service.py
  src/spaceone/identity/service/service_account_service.py
Labels: fail/signedoff

#447 fix: set default value for tags field to an empty dictionary
  src/spaceone/identity/model/user/database.py
Labels: pass/signedoff

#452 Update plugin options to include sync options
  src/spaceone/identity/service/job_service.py
Labels: enhancement, pass/signedoff

#457 feat: create workspace analyze function for metric data.
  src/spaceone/identity/interface/grpc/workspace.py
  src/spaceone/identity/manager/workspace_manager.py
  src/spaceone/identity/model/workspace/request.py
  src/spaceone/identity/service/workspace_service.py
Labels: pass/signedoff

#458 fix: Change user MFA requset payload method from unstructured format to flag
  src/spaceone/identity/model/user/request.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#460 fix: Enable OTP permission handling
  src/spaceone/identity/service/token_service.py
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#461 refactor: Updates MFA option for user enforce mfa
  src/spaceone/identity/service/user_service.py
Labels: pass/signedoff

#466 chore: Updates dependency spaceone-api/core version
  pkg/pip_requirements.txt
  src/setup.py
Labels: pass/signedoff
