Repository cloudforet-io/identity, pull requests merged in 2025-02, with the labels that each got.

#432 Fix error when updating Service Account name
  src/spaceone/identity/service/service_account_service.py
Labels: enhancement, pass/signedoff, fail/signedoff

#431 Add expiring app check scheduler
  src/spaceone/identity/conf/global_conf.py
  src/spaceone/identity/interface/task/v1/expiring_app_check_scheduler.py
  src/spaceone/identity/manager/email_manager.py
  src/spaceone/identity/service/__init__.py
  src/spaceone/identity/service/app_service.py
  src/spaceone/identity/template/domain_app_expiration_en.html
  src/spaceone/identity/template/domain_app_expiration_ja.html
  src/spaceone/identity/template/domain_app_expiration_ko.html
  src/spaceone/identity/template/workspace_app_expiration_en.html
  src/spaceone/identity/template/workspace_app_expiration_ja.html
  src/spaceone/identity/template/workspace_app_expiration_ko.html
Labels: enhancement, pass/signedoff

#433 Add expiring_app_check_scheduler to helm chart
  deploy/helm/Chart.yaml
  deploy/helm/values.yaml
Labels: enhancement, pass/signedoff

#434 feat: remove set_query_page_limit decorator at list of sa
  src/spaceone/identity/service/service_account_service.py
Labels: enhancement, pass/signedoff

#435 Remove service account query limit
  src/spaceone/identity/service/service_account_service.py
Labels: enhancement

#436 Remove limit for service account list
  src/spaceone/identity/service/service_account_service.py
Labels: enhancement
